spring.application.name=auth-service
server.port=8085

#PostgreSQL(Docker)
spring.datasource.url=jdbc:postgresql://localhost:5436/auth_db
spring.datasource.username=financeuser
spring.datasource.password=financepass

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#Kafka(Docker)
spring.kafka.bootstrap-servers=localhost:9092

#Kafka(Docker)consumer(listen for customerCreated events)
spring.kafka.consumer.group-id=auth-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Tell JsonDeserializer to use OUR local class, not the one from Customer Service
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.pm.greatadamu.authservice.kafka.CustomerEvent

# Kafka Producer Configuration for JSON
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Trust both packages (keep this)
spring.kafka.consumer.properties.spring.json.trusted.packages=com.pm.greatadamu.authservice.kafka,com.pm.greatadamu.customerservice.kafka

#JWT config
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=1800000
jwt.issuer=auth-service

#REFRESH TOKEN
auth.refresh.expiration-seconds =1209600

auth.refresh.cookie-name=REFRESH_TOKEN

# cookie hardening
auth.refresh.secure=false
auth.refresh.same-site=Lax