spring.application.name=transaction-service
server.port=8081

#PostgreSQL(Docker)-transaction db
spring.datasource.url=jdbc:postgresql://localhost:5434/transaction_db
spring.datasource.username=financeuser
spring.datasource.password=financepass

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#Kafka(Docker)
spring.kafka.bootstrap-servers=localhost:9092
#Producer config
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


grpc.account-service.host=localhost
grpc.account-service.port=9093
grpc.account-service.deadline-ms=2000




