server:
  port: ${SERVER_PORT:9090}

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cloud:
    gateway:
      server:
        webflux:
          forwarded:
            enabled: true

          httpclient:
            connect-timeout: 2000
            response-timeout: 5s

          globalcors:
            cors-configurations:
              "[/**]":
                allowed-origins:
                  - "https://your-frontend.com"
                  - "http://localhost:5173"
                allowed-methods: [GET, POST, PUT, PATCH, DELETE, OPTIONS]
                allowed-headers:
                  - Authorization
                  - Content-Type
                  - X-Requested-With
                  - Accept
                  - Origin
                allow-credentials: true
          routes:
            # -----------------------
            # AUTH SERVICE ROUTE
            # -----------------------
            - id: auth-service
              uri: ${AUTH_SERVICE_URI:http://localhost:8085}
              predicates:
                - Path=/api/auth/**

            # -----------------------
            # ACCOUNT SERVICE ROUTE
            # -----------------------
            - id: account-service
              uri: ${ACCOUNT_SERVICE_URI:http://localhost:8082}
              predicates:
                - Path=/api/accounts/**

            # -----------------------
            # CUSTOMER SERVICE ROUTE
            # -----------------------
            - id: customer-service
              uri: ${CUSTOMER_SERVICE_URI:http://localhost:8084}
              predicates:
                - Path=/api/customers/**

            # -----------------------
            # TRANSACTION SERVICE ROUTE
            # -----------------------
            - id: transaction-service
              uri: ${TRANSACTION_SERVICE_URI:http://localhost:8081}
              predicates:
                - Path=/api/transactions/**

            # -----------------------
            # ANALYTICS SERVICE ROUTE
            # -----------------------
            - id: analytic-service
              uri: ${ANALYTICS_SERVICE_URI:http://localhost:8083}
              predicates:
                - Path=/api/analytics/**


  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWKS_URI:http://localhost:8085/.well-known/jwks.json}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
