spring.application.name=customer-service

server.port=8084

#PostgreSQL(Docker)-customer Database
spring.datasource.url=jdbc:postgresql://localhost:5437/customer_db
spring.datasource.username=financeuser
spring.datasource.password=financepass

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#Kafka(Docker)
spring.kafka.bootstrap-servers=localhost:9092

# Kafka Producer (for CustomerCreated events)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false


# Kafka Consumer Configuration for JSON
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.pm.greatadamu.customerservice.kafka.UserRegisteredEvent