spring.application.name=analytics-service
server.port=8083

#PostgreSQL(Docker) Analytics Database
spring.datasource.url=jdbc:postgresql://localhost:5435/analytics_db
spring.datasource.username=financeuser
spring.datasource.password=financepass

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#Kafka(Docker)consumer
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=analytics-service
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Tell JsonDeserializer what type to turn JSON into
spring.kafka.consumer.properties.spring.json.value.default.type=com.pm.greatadamu.analyticsservice.kafka.TransactionEvent

# Allow this package for deserialization
spring.kafka.consumer.properties.spring.json.trusted.packages=com.pm.greatadamu.analyticsservice.kafka,com.pm.greatadamu.transactionservice.kafka

spring.kafka.consumer.properties.spring.json.use.type.headers=false